var ordenesPendientes = {
    "result": {
        "mensaje": "Operacion exitosa",
        "description": "Ejecucion correcta",
        "version": "1.0",
        "instancia": "Google Dev",
        "detalleOrdenes": [
            {
                "idOrden": 222122,
                "descipcionTipoOrden": "Recoleccion",
                "idSubtipoOrden": 101,
                "idFlujo": 4,
                "descripcionSubtipoOrden": "Recoleccion Equipos",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-7640234",
                "claveCliente": "0100000185",
                "nombreCliente": "Mirel Vera Delgado",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "03/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#eba2ae",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono,NUM_TICKET_SF",
                "valorAdicional": "Tickets.svg,58483",
                "idtipoOrden": 68,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Tickets.svg"
                    },
                    {
                        "nombre": "NUM_TICKET_SF",
                        "valor": "58483"
                    }
                ]
            },
            {
                "idOrden": 222119,
                "descipcionTipoOrden": "Soporte",
                "idSubtipoOrden": 116,
                "idFlujo": 2,
                "descripcionSubtipoOrden": "Soporte Con Potencia Huawei",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-6947992",
                "claveCliente": "0100000185",
                "nombreCliente": "Jose Rocha Ceval",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "03/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#EA4C31",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono",
                "valorAdicional": "ZteLogo.svg",
                "idtipoOrden": 55,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "ZteLogo.svg"
                    }
                ]
            },
            {
                "idOrden": 222123,
                "descipcionTipoOrden": "Recoleccion",
                "idSubtipoOrden": 101,
                "idFlujo": 4,
                "descripcionSubtipoOrden": "Recoleccion Equipos",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-7640234",
                "claveCliente": "0100000185",
                "nombreCliente": "Mirna Delgado Delgado",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "03/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#eba2ae",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono,NUM_TICKET_SF",
                "valorAdicional": "Tickets.svg,58483",
                "idtipoOrden": 68,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Tickets.svg"
                    },
                    {
                        "nombre": "NUM_TICKET_SF",
                        "valor": "58483"
                    }
                ]
            },
            {
                "idOrden": 222128,
                "descipcionTipoOrden": "Addon",
                "idSubtipoOrden": 120,
                "idFlujo": 3,
                "descripcionSubtipoOrden": "Adicional",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-6949029",
                "claveCliente": "0100000185",
                "nombreCliente": "Maria Priego Ceron",
                "direccion": "Av. Coyoacan 1035 12 Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "03/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#FEB431",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono,icono,NUM_TICKET_SF",
                "valorAdicional": "Vip.svg,Netflix.svg,58496395",
                "idtipoOrden": 65,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Vip.svg"
                    },
                    {
                        "nombre": "icono",
                        "valor": "Netflix.svg"
                    },
                    {
                        "nombre": "NUM_TICKET_SF",
                        "valor": "58496395"
                    }
                ]
            },
            {
                "idOrden": 222132,
                "descipcionTipoOrden": "Addon",
                "idSubtipoOrden": 120,
                "idFlujo": 3,
                "descripcionSubtipoOrden": "Adicional",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": false,
                "folioOrden": "OS-69490291",
                "claveCliente": "0100000185",
                "nombreCliente": "Marco Paez Ceron",
                "direccion": "Av. Coyoacan 1035 12 Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "03/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#FEB431",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono,NUM_TICKET_SF",
                "valorAdicional": "Netflix.svg,584963951",
                "idtipoOrden": 65,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Netflix.svg"
                    },
                    {
                        "nombre": "NUM_TICKET_SF",
                        "valor": "584963951"
                    }
                ]
            },
            {
                "idOrden": 222133,
                "descipcionTipoOrden": "Addon",
                "idSubtipoOrden": 120,
                "idFlujo": 3,
                "descripcionSubtipoOrden": "Adicional",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-69490291",
                "claveCliente": "0100000185",
                "nombreCliente": "Ulises Lucas Ceron",
                "direccion": "Av. Coyoacan 1035 12 Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "03/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#FEB431",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono,NUM_TICKET_SF",
                "valorAdicional": "Netflix.svg,584963951",
                "idtipoOrden": 65,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Netflix.svg"
                    },
                    {
                        "nombre": "NUM_TICKET_SF",
                        "valor": "584963951"
                    }
                ]
            },
            {
                "idOrden": 222106,
                "descipcionTipoOrden": "Soporte",
                "idSubtipoOrden": 116,
                "idFlujo": 2,
                "descripcionSubtipoOrden": "Soporte Con Potencia Huawei",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-6947992",
                "claveCliente": "0100000185",
                "nombreCliente": "Maria Fernanda Rocha Ceval",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "02/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#EA4C31",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono",
                "valorAdicional": "Huawei.svg",
                "idtipoOrden": 55,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Huawei.svg"
                    }
                ]
            },
            {
                "idOrden": 222105,
                "descipcionTipoOrden": "Soporte",
                "idSubtipoOrden": 116,
                "idFlujo": 2,
                "descripcionSubtipoOrden": "Soporte Con Potencia Huawei",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-6947992",
                "claveCliente": "0100000185",
                "nombreCliente": "Maria Fernanda Rocha Ceval",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "02/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#EA4C31",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono",
                "valorAdicional": "Huawei.svg",
                "idtipoOrden": 55,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Huawei.svg"
                    }
                ]
            },
            {
                "idOrden": 222127,
                "descipcionTipoOrden": "Addon",
                "idSubtipoOrden": 120,
                "idFlujo": 3,
                "descripcionSubtipoOrden": "Adicional",
                "idTurno": 1,
                "descripcionTurno": "Matutino",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "ordenConfirmada": true,
                "folioOrden": "OS-6949029",
                "claveCliente": "0100000185",
                "nombreCliente": "Karen Aguilar Ceron",
                "direccion": "Av. Coyoacan 1035 12 Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "fechaAgenda": "02/02/2022",
                "horaAgenda": "00:35",
                "colorOrden": "#FEB431",
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#0050a1",
                "colorOverEstatus": "#fb6432",
                "nombreAdicional": "icono,icono,NUM_TICKET_SF",
                "valorAdicional": "Vip.svg,Netflix.svg,58496395",
                "idtipoOrden": 65,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Vip.svg"
                    },
                    {
                        "nombre": "icono",
                        "valor": "Netflix.svg"
                    },
                    {
                        "nombre": "NUM_TICKET_SF",
                        "valor": "58496395"
                    }
                ]
            }
        ]
    },
    "resultDescripcion": "Accion completada",
    "mensajeException": null,
    "respuesta": true
}

var ordenesAsignadas = {
    "result": {
        "mensaje": "Operacion exitosa",
        "description": "Ejecucion correcta",
        "version": "1.0",
        "instancia": "Google Dev",
        "detalleOrdenesAsignadas": [
            {
                "idOrden": 219032,
                "descipcionTipoOrden": "Instalacion",
                "idSubtipoOrden": 106,
                "idFlujo": 1,
                "descripcionSubtipoOrden": "Instalacion Huawei",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "folioOrden": "OS-7640234",
                "claveCliente": "0100000185",
                "nombreCliente": "Gamaliel Aguilar Ceron",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "colorOrden": "#C1CF00",
                "idTecnico": 79642,
                "fechaInicio": "2022-01-20",
                "horaInicio": "13:19",
                "fechaFin": "2022-01-20",
                "horaFin": "20:30",
                "tipoAsignacion": 2,
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#1667b8",
                "colorOverEstatus": "#1f6ab5",
                "nombreAdicional": "icono",
                "valorAdicional": "Huawei.svg",
                "idtipoOrden": 48,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Huawei.svg"
                    }
                ]
            },
            {
                "idOrden": 219033,
                "descipcionTipoOrden": "Instalacion",
                "idSubtipoOrden": 106,
                "idFlujo": 1,
                "descripcionSubtipoOrden": "Instalacion Huawei",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "folioOrden": "OS-7640234",
                "claveCliente": "0100000185",
                "nombreCliente": "Gamaliel Aguilar Ceron",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "colorOrden": "#C1CF00",
                "idTecnico": 79642,
                "fechaInicio": "2022-01-20",
                "horaInicio": "13:19",
                "fechaFin": "2022-01-20",
                "horaFin": "20:30",
                "tipoAsignacion": 2,
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#1667b8",
                "colorOverEstatus": "#1f6ab5",
                "nombreAdicional": "icono",
                "valorAdicional": "Huawei.svg",
                "idtipoOrden": 48,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Huawei.svg"
                    }
                ]
            },
            {
                "idOrden": 219034,
                "descipcionTipoOrden": "Instalacion",
                "idSubtipoOrden": 106,
                "idFlujo": 1,
                "descripcionSubtipoOrden": "Instalacion Huawei",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "folioOrden": "OS-7640234",
                "claveCliente": "0100000185",
                "nombreCliente": "Gamaliel Aguilar Ceron",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "colorOrden": "#C1CF00",
                "idTecnico": 79642,
                "fechaInicio": "2022-01-20",
                "horaInicio": "13:19",
                "fechaFin": "2022-01-20",
                "horaFin": "20:30",
                "tipoAsignacion": 2,
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#1667b8",
                "colorOverEstatus": "#1f6ab5",
                "nombreAdicional": "icono",
                "valorAdicional": "Huawei.svg",
                "idtipoOrden": 48,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Huawei.svg"
                    }
                ]
            },
            {
                "idOrden": 219035,
                "descipcionTipoOrden": "Instalacion",
                "idSubtipoOrden": 106,
                "idFlujo": 1,
                "descripcionSubtipoOrden": "Instalacion Huawei",
                "idGeografia": 3160,
                "descripcionGeografia": "Pedregal",
                "folioOrden": "OS-7640234",
                "claveCliente": "0100000185",
                "nombreCliente": "Gamaliel Aguilar Ceron",
                "direccion": "Av. Coyoacan 1035 Gdjej 12 Swesdds Del Valle 450000 Ciudad De Mexico",
                "telefono": "5587652300",
                "colorOrden": "#C1CF00",
                "idTecnico": 79642,
                "fechaInicio": "2022-01-20",
                "horaInicio": "13:19",
                "fechaFin": "2022-01-20",
                "horaFin": "20:30",
                "tipoAsignacion": 2,
                "numVisista": 0,
                "latitud": 19.336114067048,
                "longitud": -99.1969629133,
                "colorEstatus": "#1667b8",
                "colorOverEstatus": "#1f6ab5",
                "nombreAdicional": "icono",
                "valorAdicional": "Huawei.svg",
                "idtipoOrden": 48,
                "informacionAdicional": [
                    {
                        "nombre": "icono",
                        "valor": "Huawei.svg"
                    }
                ]
            }

        ]
    },
    "resultDescripcion": "Accion completada",
    "mensajeException": null,
    "respuesta": true
}

var tecnicosLista = {
    "result": {
        "mensaje": "Operacion exitosa",
        "description": "Ejecucion correcta",
        "version": "1.0",
        "instancia": "Google Dev",
        "detalleTecnicos": [
            {
                "idTecnico": 79647,
                "idEstatusTecnico": 5,
                "descipcionEstatusTecnico": "Fuera De Servicio",
                "numeroEmpleado": "6506734",
                "usuarioFFM": "6506734",
                "numContacto": "8888888888",
                "nombre": "Antonio",
                "apellidoPaterno": "Rodriguez",
                "apellidoMaterno": "Calderon",
                "urlFotoPerfil": "https://firebasestorage.googleapis.com/v0/b/totalplay-ffm-core-dev.appspot.com/o/usuarios%2Fmex%2F6506734%2FfotoPerfil?alt=media&token=uuidv4()",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#2424257d",
                "geografias": "2047",
                "tiposOrdenes": "101,105,107,115,120,123,124",
                "idClusters": [
                    2047
                ],
                "idSubIntervenciones": [
                    101,
                    105,
                    107,
                    115,
                    120,
                    123,
                    124
                ]
            },
            {
                "idTecnico": 79641,
                "idEstatusTecnico": 5,
                "descipcionEstatusTecnico": "Fuera De Servicio",
                "numeroEmpleado": "65067362",
                "usuarioFFM": "65067362",
                "numContacto": "7777280212",
                "nombre": "App Issac",
                "apellidoPaterno": "test",
                "apellidoMaterno": "test",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#2424257d",
                "latitud": 19.3339792,
                "longitud": -99.1986673,
                "geografias": "2047",
                "tiposOrdenes": "101,115,120,123,124,125,126",
                "idClusters": [
                    2047
                ],
                "idSubIntervenciones": [
                    101,
                    115,
                    120,
                    123,
                    124,
                    125,
                    126
                ]
            },
            {
                "idTecnico": 79642,
                "idEstatusTecnico": 3,
                "descipcionEstatusTecnico": "Comida",
                "numeroEmpleado": "PRUEBASPI",
                "usuarioFFM": "PRUEBASPI",
                "numContacto": "2376237623",
                "nombre": "Gamaliel",
                "apellidoPaterno": "Aguilar",
                "apellidoMaterno": "Ceron",
                "urlFotoPerfil": "https://firebasestorage.googleapis.com/v0/b/totalplay-ffm-core-dev.appspot.com/o/userProfilePhoto?alt=media&token=uuidv4()",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#a61daf",
                "latitud": 19.3385592,
                "longitud": -99.195612,
                "geografias": "2047",
                "tiposOrdenes": "100,101,102,104,105,106,107,115,116,120,121,122,123,124,125",
                "idClusters": [
                    2047
                ],
                "idSubIntervenciones": [
                    100,
                    101,
                    102,
                    104,
                    105,
                    106,
                    107,
                    115,
                    116,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125
                ]
            },
            {
                "idTecnico": 79644,
                "idEstatusTecnico": 2,
                "descipcionEstatusTecnico": "Ocupado",
                "numeroEmpleado": "15015902",
                "usuarioFFM": "TECNICOPI1",
                "numContacto": "5523377698",
                "nombre": "Juan Carlos",
                "apellidoPaterno": "Garcia",
                "apellidoMaterno": "Priego",
                "urlFotoPerfil": "https://firebasestorage.googleapis.com/v0/b/totalplay-ffm-core-dev.appspot.com/o/usuarios%2Fmex%2F15015902%2FfotoPerfil.jpg?alt=media&token=uuidv4()",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#f02d4f",
                "latitud": 19.3341526,
                "longitud": -99.1987247,
                "geografias": "2131",
                "tiposOrdenes": "120,121,122,123,124,125",
                "idClusters": [
                    2131
                ],
                "idSubIntervenciones": [
                    120,
                    121,
                    122,
                    123,
                    124,
                    125
                ]
            },
            {
                "idTecnico": 125471,
                "idEstatusTecnico": 5,
                "descipcionEstatusTecnico": "Fuera De Servicio",
                "numeroEmpleado": "65030867",
                "usuarioFFM": "65067688",
                "numContacto": "1111111111111",
                "nombre": "Karla",
                "apellidoPaterno": "Camacho",
                "apellidoMaterno": "Dominguez",
                "urlFotoPerfil": "https://firebasestorage.googleapis.com/v0/b/totalplay-ffm-core-dev.appspot.com/o/KARLA MONTSERRAT CAMACHO DOMINGUEZ?alt=media&token=uuidv4()",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#2424257d",
                "latitud": 19.3342413,
                "longitud": -99.1986526,
                "geografias": "2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2042,2043,2044,2045,2046,2047,2048,2057,2086,2142,2143,2144,2145,2147,2148,2149,2164,2165,2166,2167,2195",
                "tiposOrdenes": "100,101,102,104,105,106,107,115,116,117,118,119,120,121,122,123,124,125",
                "idClusters": [
                    2005,
                    2006,
                    2007,
                    2008,
                    2011,
                    2012,
                    2013,
                    2014,
                    2015,
                    2016,
                    2017,
                    2018,
                    2019,
                    2020,
                    2042,
                    2043,
                    2044,
                    2045,
                    2046,
                    2047,
                    2048,
                    2057,
                    2086,
                    2142,
                    2143,
                    2144,
                    2145,
                    2147,
                    2148,
                    2149,
                    2164,
                    2165,
                    2166,
                    2167,
                    2195
                ],
                "idSubIntervenciones": [
                    100,
                    101,
                    102,
                    104,
                    105,
                    106,
                    107,
                    115,
                    116,
                    117,
                    118,
                    119,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125
                ]
            },
            {
                "idTecnico": 2,
                "idEstatusTecnico": 1,
                "descipcionEstatusTecnico": "En Linea",
                "numeroEmpleado": "14102832",
                "usuarioFFM": "FFMBACK",
                "numContacto": "5532890753",
                "nombre": "Luis",
                "apellidoPaterno": "Lopez",
                "apellidoMaterno": "Perez",
                "urlFotoPerfil": "https://firebasestorage.googleapis.com/v0/b/totalplay-ffm-core-dev.appspot.com/o/userProfilePhoto?alt=media&token=uuidv4()",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#5cbc5c",
                "latitud": 19.3341539,
                "longitud": -99.1986908,
                "geografias": "2047",
                "tiposOrdenes": "100,101,102,104,105,106,107,109,110,111,112,113,115,116,117,118,119,120,121,122,123,124,125,126",
                "idClusters": [
                    2047
                ],
                "idSubIntervenciones": [
                    100,
                    101,
                    102,
                    104,
                    105,
                    106,
                    107,
                    109,
                    110,
                    111,
                    112,
                    113,
                    115,
                    116,
                    117,
                    118,
                    119,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125,
                    126
                ]
            },
            {
                "idTecnico": 79663,
                "idEstatusTecnico": 1,
                "descipcionEstatusTecnico": "En Linea",
                "numeroEmpleado": "65030867",
                "usuarioFFM": "15015041",
                "numContacto": "5500000000",
                "nombre": "Ricardo",
                "apellidoPaterno": "González",
                "apellidoMaterno": "Luna",
                "urlFotoPerfil": "https://firebasestorage.googleapis.com/v0/b/totalplay-ffm-core-dev.appspot.com/o/usuarios%2Fmex%2F65030867%2FfotoPerfil?alt=media&token=uuidv4()",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#5cbc5c",
                "latitud": 19.334139,
                "longitud": -99.1987001,
                "geografias": "2047",
                "tiposOrdenes": "100,101,102,104,105,106,107,115,116,120,121,122,123,124,125",
                "idClusters": [
                    2047
                ],
                "idSubIntervenciones": [
                    100,
                    101,
                    102,
                    104,
                    105,
                    106,
                    107,
                    115,
                    116,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125
                ]
            },
            {
                "idTecnico": 22,
                "idEstatusTecnico": 1,
                "descipcionEstatusTecnico": "En Linea",
                "numeroEmpleado": "65030867",
                "usuarioFFM": "TECNICOPI",
                "numContacto": "236732763276",
                "nombre": "Tecnico",
                "apellidoPaterno": "Planta",
                "apellidoMaterno": "Interna",
                "urlFotoPerfil": "https://firebasestorage.googleapis.com/v0/b/totalplay-ffm-core-dev.appspot.com/o/userProfilePhoto?alt=media&token=uuidv4()",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#5cbc5c",
                "latitud": 19.2994409,
                "longitud": -99.2598541,
                "geografias": "2047",
                "tiposOrdenes": "101,102,104,105,107,109,110,111,112,113,115,120,122,123,124,125,126",
                "idClusters": [
                    2047
                ],
                "idSubIntervenciones": [
                    101,
                    102,
                    104,
                    105,
                    107,
                    109,
                    110,
                    111,
                    112,
                    113,
                    115,
                    120,
                    122,
                    123,
                    124,
                    125,
                    126
                ]
            },
            {
                "idTecnico": 79635,
                "idEstatusTecnico": 5,
                "descipcionEstatusTecnico": "Fuera De Servicio",
                "numeroEmpleado": "15015990",
                "usuarioFFM": "tec15015990",
                "numContacto": "5500000000",
                "nombre": "Tecnico",
                "apellidoPaterno": "Primerape",
                "apellidoMaterno": "Segundoape",
                "idTipoUsuario": 7,
                "descripcionTipoUsuario": "Tecnico",
                "color": "#2424257d",
                "geografias": "2047",
                "tiposOrdenes": "101,102,115,120,122,123,124,125,126",
                "idClusters": [
                    2047
                ],
                "idSubIntervenciones": [
                    101,
                    102,
                    115,
                    120,
                    122,
                    123,
                    124,
                    125,
                    126
                ]
            }
        ]
    },
    "resultDescripcion": "Accion completada",
    "mensajeException": null,
    "respuesta": true
}