app.graficaController = function ($scope, $q, misProyectosService) {

    $scope.lineaTiempo = {};

    $scope.inicializarGrafica = function() {
        //Se itera la lista de proyectos para obtener la fecha inicio y fecha fin de la grafica
        
        $scope.heightCalendar = 50;

        $scope.lineaTiempo.fechaInicio = new Date();
        $scope.lineaTiempo.fechaFin = new Date();

        $scope.listaProyectosGrafica.map(function(proyecto, index) {

            if (true) {
                
            }
        });

        console.log($scope.listaProyectosGrafica);
    }

    $scope.resultProyectos = 
    {
        "success": true,
        "result": {
            "result": "0",
            "resultDescripcion": "Operacion_exitosa",
            "version": "1.2",
            "Num_total_planes": "11",
            "Num_en_tiempo": "0",
            "Num_en_riesgo": "0",
            "Num_fuera_tiempo": "0",
            "Num_pendientes": "30",
            "OS_pendientes": "30",
            "Num_confirmado": "0",
            "Num_proceso": "0",
            "Num_restcate": "0",
            "Num_Cancelado": "0",
            "Num_detenida": "0",
            "Num_gestoria": "0",
            "Num_suspendido": "0",
            "Num_completado": "0",
            "Num_calendarizado": "0",
            "Num_otro": "0",
            "totalPuntas": "30",
            "totalPuntasPorInstalar": "30",
            "totalPuntasCalendarizado": "0",
            "totalPuntasDetenido": "0",
            "totalPuntasDevueltoVentas": "0",
            "totalPuntasCancelado": "0",
            "totalPuntasInstalado": "0",
            "Proyectos": [{
                "Id_cuenta": "0018A00000iXrXkQAK",
                "Nombre_cliente": "Test Troncales",
                "Es_Top_5000": "false",
                "Segmento": "Pequenas",
                "Sector": "Servicios",
                "Nombre_contacto": "Testtroncalestest",
                "Tel_contacto": "5500000012",
                "Num_fuera_tiempo": "0",
                "Num_en_riesgo": "0",
                "Num_en_tiempo": "0",
                "Num_pendientes": "30",
                "OS_pendientes": "30",
                "Num_confirmado": "0",
                "Num_proceso": "0",
                "Num_restcate": "0",
                "Num_Cancelado": "0",
                "Num_detenida": "0",
                "Num_gestoria": "0",
                "Num_suspendido": "0",
                "Num_completado": "0",
                "Num_calendarizado": "0",
                "Num_otro": "0",
                "totalPuntas": "30",
                "totalPuntasPorInstalar": "30",
                "totalPuntasCalendarizado": "0",
                "totalPuntasDetenido": "0",
                "totalPuntasDevueltoVentas": "0",
                "totalPuntasCancelado": "0",
                "totalPuntasInstalado": "0",
                "fechaInicioPlaneada": "",
                "fechaFinPlaneada": "",
                "fechaInicioReal": "",
                "fechaFinReal": "",
                "fechaActual": "12-28-2021",
                "porcentajeAvance": ".00",
                "porcentajeEsperado": "",
                "semaforo": "",
                "informacionCliente": {
                    "razonSocial": "Test Troncales",
                    "rfc": "XXX000001XX8",
                    "top5000": "false",
                    "ciudad": "CDMX",
                    "estado": "Ciudad de México",
                    "delegacionMunicipio": "Coyoacán",
                    "colonia": "La Otra Banda",
                    "calle": "Avenida San Jerónimo",
                    "numeroExterior": "252",
                    "numeroInterior": "10",
                    "codigoPostal": "04519",
                    "phone": "5500000012",
                    "montoPotencial": "De $1,000 a $30,000",
                    "contactoPrincipalNombreCompleto": "TestTroncalesTest",
                    "contactoPrincipalPhone": "5500000012",
                    "contactoPrincipalEmail": "testtroncales@test.com"
                },
                "Puntas": [{
                    "Id_cuenta": "0018A00000iXrXkQAK",
                    "Id_cotizacion": "a068A000003w05mQAA",
                    "Folio_cotizacion": "COT4095673",
                    "Id_oportunidad": "0068A00000B5cc4QAB",
                    "Numero_oportunidad": "04043899",
                    "Id_cot_sitio": "a128A000003P6kyQAC",
                    "Nombre_cot_sitio": "CS5004641",
                    "Id_sitio": "a018A000005ULsyQAG",
                    "Folio_sitio": "SIT-4016791",
                    "Nombre_sitio": "Sit1-TestTroncales",
                    "esVenta": "true",
                    "Fecha_cierre": "23/12/2021",
                    "Plazo": "36",
                    "Nombre_responsable_sitio": "Marco Hernandez Miron",
                    "Longitud": "19.334342",
                    "Latitud": "-99.19896299999999",
                    "Plaza": "Ciudad De Mexico",
                    "Direccion_sitio": "Avenida San Jerónimo, 112 , La Otra Banda, Ciudad De México, 04519",
                    "esNueva": "false",
                    "fechaInicioPlaneada": "",
                    "fechaFinPlaneada": "",
                    "fechaInicioReal": "",
                    "fechaFinReal": "",
                    "fechaActual": "12-28-2021",
                    "porcentajeAvance": ".00",
                    "porcentajeEsperado": "",
                    "semaforo": "",
                    "Num_fuera_tiempo": "0",
                    "Num_en_riesgo": "0",
                    "Num_en_tiempo": "0",
                    "Num_pendientes": "10",
                    "OS_pendientes": "10",
                    "Num_confirmado": "0",
                    "Num_proceso": "0",
                    "Num_restcate": "0",
                    "Num_Cancelado": "0",
                    "Num_detenida": "0",
                    "Num_gestoria": "0",
                    "Num_suspendido": "0",
                    "Num_completado": "0",
                    "Num_calendarizado": "0",
                    "Num_otro": "0",
                    "Num_total": "11",
                    "totalPuntas": "10",
                    "totalPuntasPorInstalar": "10",
                    "totalPuntasCalendarizado": "0",
                    "totalPuntasDetenido": "0",
                    "totalPuntasDevueltoVentas": "0",
                    "totalPuntasCancelado": "0",
                    "totalPuntasInstalado": "0",
                    "estatusPlaneacion": "0",
                    "enTiempo": "",
                    "informacionContrato": {
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999"
                    },
                    "Planes": [{
                        "idVendedor": "0058A000003F6ZjQAK",
                        "idDetallePlaneacion": "1422",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rcQAC",
                        "Folio_CSP": "CSP5701933",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGofUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000446",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": ".00",
                        "porcentajeEsperado": "",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701933",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000446",
                            "cuadrillaFFM": "Empresarial"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rdQAC",
                        "Folio_CSP": "CSP5701934",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGogUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000447",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701934",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000447",
                            "cuadrillaFFM": "Empresarial"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3raQAC",
                        "Folio_CSP": "CSP5701931",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGodUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000444",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701931",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000444",
                            "cuadrillaFFM": "Empresarial"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rbQAC",
                        "Folio_CSP": "CSP5701932",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGoeUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000445",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701932",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000445",
                            "cuadrillaFFM": "Empresarial"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rZQAS",
                        "Folio_CSP": "CSP5701930",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGocUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000443",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701930",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000443",
                            "cuadrillaFFM": "Empresarial"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rXQAS",
                        "Folio_CSP": "CSP5701928",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGoaUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000441",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701928",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000441",
                            "cuadrillaFFM": "Empresarial",
                            "estatusActivacion": "En proceso"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerEstatusActivacion": "En proceso",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rYQAS",
                        "Folio_CSP": "CSP5701929",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGobUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000442",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701929",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000442",
                            "cuadrillaFFM": "Empresarial"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rVQAS",
                        "Folio_CSP": "CSP5701926",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGoYUAU",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000439",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701926",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000439",
                            "cuadrillaFFM": "Empresarial",
                            "estatusActivacion": "En proceso"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerEstatusActivacion": "En proceso",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3rWQAS",
                        "Folio_CSP": "CSP5701927",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGoZUAU",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000440",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701927",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000440",
                            "cuadrillaFFM": "Empresarial",
                            "estatusActivacion": "En proceso"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerEstatusActivacion": "En proceso",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }, {
                        "idVendedor": "0058A000003F6ZjQAK",
                        "Id_cuenta": "0018A00000iXrXkQAK",
                        "Id_cot_sitio": "a128A000003P6kyQAC",
                        "Id_csp": "a118A000001G3reQAC",
                        "Folio_CSP": "CSP5701935",
                        "Paquete": "Troncal SIP 10x30 Empresarial TE",
                        "esVenta": "true",
                        "tipoImplementacion": "Nueva",
                        "Canal_venta": "Sin espesificar",
                        "BannerFamiliaPlan": "Troncales SIP Empresarial TE",
                        "Tipo_cuadrilla": "Empresarial",
                        "Tipo_acceso": "FIBRA",
                        "Unidad_negocio": "2",
                        "Tipo_intervencion": "48",
                        "Subtipo_intervencion": "49",
                        "Region": "MEGACENTRO",
                        "Ciudad": "CIUDAD DE MEXICO",
                        "Distrito": "SUR",
                        "Cluster": "PEDREGAL",
                        "Calle": "Avenida San Jerónimo",
                        "Colonia": "La Otra Banda",
                        "Estado": "Ciudad de México",
                        "Municipio": "Ciudad de México",
                        "Num_exterior": "112",
                        "Latitud": "19.334342",
                        "Longitud": "-99.19896299999999",
                        "CP": "04519",
                        "Telefono_contacto": "5500000012",
                        "Id_cuenta_factura": "a0G8A000004cGohUAE",
                        "Status_OS": "Pendiente",
                        "statusCsp": "Por instalar",
                        "tipoPlan": "P",
                        "Numero_cuentaFactura": "0200000448",
                        "fechaInicioPlaneada": "",
                        "fechaFinPlaneada": "",
                        "fechaInicioReal": "",
                        "fechaFinReal": "",
                        "fechaActual": "12-28-2021",
                        "porcentajeAvance": "0.0",
                        "porcentajeEsperado": "0.0",
                        "semaforo": "",
                        "PlaneacionCerrada": "false",
                        "implementacionterminada": "false",
                        "estatusPlaneacion": "0",
                        "enTiempo": "",
                        "informacionServicio": {
                            "folioCsp": "CSP5701935",
                            "familiaPlan": "Troncales SIP Empresarial TE",
                            "nombrePlan": "Troncal SIP 10x30 Empresarial TE",
                            "tipoOportunidad": "Nueva",
                            "tipoRegistro": "IP",
                            "acessoPrincipal": "FIBRA",
                            "TipoCotizacionPm": "Planes",
                            "cuentaFactura": "0200000448",
                            "cuadrillaFFM": "Empresarial"
                        },
                        "folioCotSitio": "CS5004641",
                        "direccionSitio": "",
                        "plaza": "CIUDAD DE MEXICO",
                        "subtotalRenta": "20990.0",
                        "totalRentaConImpuesto": "25078.9",
                        "tipoOportunidad": "Planes",
                        "folioCotizacion": "COT4095673",
                        "nombreSitio": "Sit1-TestTroncales",
                        "folioSitio": "SIT-4016791",
                        "tipoCobertura": "Sólo fibra",
                        "latitude": "19.334342",
                        "longitude": "-99.19896299999999",
                        "BannerTipoCotizacionPM": "Planes",
                        "BannerTipo_de_registro_CF": "IP"
                    }],
                    "listStatusOS": ["Pendiente", "Pendiente", "Pendiente", "Pendiente", "Pendiente", "Pendiente", "Pendiente", "Pendiente", "Pendiente", "Pendiente"],
                    "listStatusCSP": ["Por instalar", "Por instalar", "Por instalar", "Por instalar", "Por instalar", "Por instalar", "Por instalar", "Por instalar", "Por instalar", "Por instalar"],
                    "listSemaforo": ["", "", "", "", "", "", "", "", "", ""]
                }],
                "Num_total": "11"
            }]
        }
    }

    $scope.resultActividades = 
    {
        "success": true,
        "result": {
            "result": "0",
            "resultDescripcion": "Operacion_exitosa",
            "Version": "1.2",
            "Num_en_tiempo": "0",
            "Num_en_riesgo": "0",
            "Num_fuera_tiempo": "0",
            "Num_pendientes": "4",
            "Actividades": [{
                "Id_actividad": "3665",
                "orden": "1",
                "Id_tipo_actividad": "1",
                "Nombre_actividad": "Validacion Con El Cliente Y Generacion Del Plana De Trabajo",
                "Nombre_responsable": "",
                "Porcentaje": "0",
                "Fecha_inicio_planeada": "",
                "Fecha_fin_planeada": "",
                "Fecha_inicio_real": "",
                "Fecha_fin_real": "",
                "Id_dependencia": "",
                "Fecha_creacion": "2021-12-28 00:00:00",
                "Se_puede_eliminar": "false",
                "Tiene_Ot": "false",
                "Id_implementacion": "1422",
                "Id_csp": "a118A000001G3rcQAC",
                "hoy": "12-30-2021",
                "planeacionCerrada": "0",
                "planTermindo": "1",
                "enTiempo": "false"
            }, {
                "Id_actividad": "3666",
                "orden": "2",
                "Id_tipo_actividad": "2",
                "Nombre_actividad": "Implementacion Del Servicio",
                "Nombre_responsable": "",
                "Porcentaje": "0",
                "Fecha_inicio_planeada": "",
                "Fecha_fin_planeada": "",
                "Fecha_inicio_real": "",
                "Fecha_fin_real": "",
                "Id_dependencia": "3665",
                "Fecha_creacion": "2021-12-28 00:00:00",
                "Se_puede_eliminar": "false",
                "Tiene_Ot": "true",
                "Id_implementacion": "1422",
                "Id_csp": "a118A000001G3rcQAC",
                "hoy": "12-30-2021",
                "planeacionCerrada": "0",
                "planTermindo": "1",
                "enTiempo": "false"
            }, {
                "Id_actividad": "3667",
                "orden": "3",
                "Id_tipo_actividad": "3",
                "Nombre_actividad": "Pruebas Del Servicio",
                "Nombre_responsable": "",
                "Porcentaje": "0",
                "Fecha_inicio_planeada": "",
                "Fecha_fin_planeada": "",
                "Fecha_inicio_real": "",
                "Fecha_fin_real": "",
                "Id_dependencia": "3666",
                "Fecha_creacion": "2021-12-28 00:00:00",
                "Se_puede_eliminar": "false",
                "Tiene_Ot": "false",
                "Id_implementacion": "1422",
                "Id_csp": "a118A000001G3rcQAC",
                "hoy": "12-30-2021",
                "planeacionCerrada": "0",
                "planTermindo": "1",
                "enTiempo": "false"
            }, {
                "Id_actividad": "3668",
                "orden": "4",
                "Id_tipo_actividad": "4",
                "Nombre_actividad": "Entrega Del Servicio",
                "Nombre_responsable": "",
                "Porcentaje": "0",
                "Fecha_inicio_planeada": "",
                "Fecha_fin_planeada": "",
                "Fecha_inicio_real": "",
                "Fecha_fin_real": "",
                "Id_dependencia": "3667",
                "Fecha_creacion": "2021-12-28 00:00:00",
                "Se_puede_eliminar": "false",
                "Tiene_Ot": "false",
                "Id_implementacion": "1422",
                "Id_csp": "a118A000001G3rcQAC",
                "hoy": "12-30-2021",
                "planeacionCerrada": "0",
                "planTermindo": "1",
                "enTiempo": "false"
            }],
            "dependencia": "SIN DEPENDENCIA",
            "idDependencia": "0"
        }
    };
    
};

