var jsonBusqGral = 
{
    "mensaje": "Operacion exitosa",
    "description": "consulta realizada correctamente",
    "version": "1",
    "instancia": null,
    "puntas": [
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      },
      {
        "idOportunidad": "1",
        "nombreOportunoidad": "Audi",
        "numOportubidad": "989",
        "vertical": "Estrategias IV",
        "celula": "Sur",
        "cliente": "Audi",
        "plazaVenta": "Plaza 123",
        "plazaInstalacion": "Plaza Inst 28",
        "idCotizacion": "Cot-124",
        "cotizacion": "Cot-880",
        "idCsp": "Id - 189",
        "csp": "CSP13234013",
        "idEim": "2",
        "nombreEim": "Aldo Camacho",
        "idVendedor": "43",
        "nombreVendedor": "Susana Ambriz",
        "idLiderTecnico": "Lucian Tristana",
        "nombreLiderTecnico": "Miss Warwick",
        "idTorreControl": "43",
        "nombreTorreControl": "Esta es la torre",
        "tipoCuadrilla": "Cerrada",
        "esTop5000": "23",
        "fechaVenta": "22/09/2022"
      }
      
    ]
  }